//! Golden-fixture harness: loads the committed fixtures under `fixtures/`
//! (generated by `tools/golden-gen/`, never hand-edited) and compares
//! rustprop results against upstream CoolProp 8.0.0 values under the PLAN.md
//! tolerance policy.
//!
//! All golden tests live in this crate (it grows dev-dependencies on the
//! facade as engines land), so shipped crates never depend on it. This crate
//! is also the only place outside dev tooling where serde/JSON is allowed.

use std::path::Path;

/// Every full-battery HEOS fluid: (upstream name, fixture/module stem, data).
/// The stem follows rustprop-datagen's `module_name` convention and names
/// both the generated data module and the `heos_<stem>_<suite>.jsonl`
/// fixtures.
///
/// The first six are the Phase 4.1–4.7 fluids (Water plus one per term family
/// reached there). The last six are Phase 4.8's representatives of the six
/// term families that slice added — CP0Constant (Fluorine), CP0PolyT
/// (Methanol), CP0AlyLee (n-Heptane), direct PlanckEinsteinGeneralized
/// (R125), Exponential (R22), DoubleExponential/Lemmon2005 (RC318). 4.8
/// generated their seven-suite batteries and reported them green, but never
/// added them to this list, so nothing read those 4,662 records until Wave-3
/// R9 wired them in.
pub fn heos_fluids() -> [(
    &'static str,
    &'static str,
    &'static rustprop_core::fluid::FluidData,
); 12] {
    [
        ("Water", "water", &rustprop_data::fluids::water::WATER),
        (
            "Nitrogen",
            "nitrogen",
            &rustprop_data::fluids::nitrogen::NITROGEN,
        ),
        (
            "CarbonDioxide",
            "carbondioxide",
            &rustprop_data::fluids::carbondioxide::CARBONDIOXIDE,
        ),
        ("R134a", "r134a", &rustprop_data::fluids::r134a::R134A),
        (
            "n-Propane",
            "n_propane",
            &rustprop_data::fluids::n_propane::N_PROPANE,
        ),
        (
            "Ammonia",
            "ammonia",
            &rustprop_data::fluids::ammonia::AMMONIA,
        ),
        (
            "Fluorine",
            "fluorine",
            &rustprop_data::fluids::fluorine::FLUORINE,
        ),
        (
            "Methanol",
            "methanol",
            &rustprop_data::fluids::methanol::METHANOL,
        ),
        (
            "n-Heptane",
            "n_heptane",
            &rustprop_data::fluids::n_heptane::N_HEPTANE,
        ),
        ("R125", "r125", &rustprop_data::fluids::r125::R125),
        ("R22", "r22", &rustprop_data::fluids::r22::R22),
        ("RC318", "rc318", &rustprop_data::fluids::rc318::RC318),
    ]
}

/// One oracle observation: `PropsSI(out, name1, val1, name2, val2,
/// "backend::fluid") == expected`, generated by `tools/golden-gen/`.
#[derive(Debug, serde::Deserialize)]
pub struct GoldenRecord {
    pub backend: String,
    pub fluid: String,
    pub out: String,
    pub name1: String,
    pub val1: f64,
    pub name2: String,
    pub val2: f64,
    /// Third input of the humid-air triples (absent elsewhere).
    #[serde(default)]
    pub name3: String,
    #[serde(default)]
    pub val3: f64,
    pub expected: f64,
    /// Per-record override of the suite's default relative tolerance.
    #[serde(default)]
    pub rtol: Option<f64>,
    /// Present only on ERROR-PARITY records: the oracle REFUSES this state and
    /// carries its verbatim message here, `expected` being a placeholder 0.0
    /// (JSON Lines has no NaN literal). A suite that reads this field must
    /// require the port to refuse the state too.
    #[serde(default)]
    pub error: Option<String>,
}

impl GoldenRecord {
    /// Human-readable identity for failure messages.
    pub fn id(&self) -> String {
        format!(
            "{}({}={},{}={},{}::{})",
            self.out, self.name1, self.val1, self.name2, self.val2, self.backend, self.fluid
        )
    }
}

/// Loads a JSON Lines fixture file. Panics on any I/O or parse error —
/// in test code a broken fixture must fail loudly.
pub fn load_jsonl(path: &Path) -> Vec<GoldenRecord> {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("cannot read fixture {}: {e}", path.display()));
    text.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| {
            serde_json::from_str(l)
                .unwrap_or_else(|e| panic!("bad fixture line in {}: {e}\n{l}", path.display()))
        })
        .collect()
}

/// Checks `actual` against the record under its tolerance (or `default_rtol`).
/// Exact equality always passes (legitimate zero-valued fixtures exist: the
/// mixture `d2alpha0_dDelta_dTau` is identically zero). Otherwise relative
/// comparison only: a zero `expected` yields an infinite (or NaN) relative
/// error for any disagreeing `actual`, which fails loudly.
pub fn check(rec: &GoldenRecord, actual: f64, default_rtol: f64) -> Result<(), String> {
    if actual == rec.expected {
        return Ok(());
    }
    let rtol = rec.rtol.unwrap_or(default_rtol);
    let rel = ((actual - rec.expected) / rec.expected).abs();
    if rel <= rtol {
        Ok(())
    } else {
        Err(format!(
            "{}: actual {actual:e} vs expected {:e} (rel err {rel:e} > rtol {rtol:e})",
            rec.id(),
            rec.expected,
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rec(expected: f64, rtol: Option<f64>) -> GoldenRecord {
        GoldenRecord {
            backend: "HEOS".into(),
            fluid: "Water".into(),
            out: "T".into(),
            name1: "P".into(),
            val1: 101325.0,
            name2: "Q".into(),
            val2: 0.0,
            name3: String::new(),
            val3: 0.0,
            expected,
            rtol,
            error: None,
        }
    }

    #[test]
    fn known_good_passes() {
        let r = rec(373.124295847666, None);
        check(&r, 373.124295847666, 1e-9).unwrap();
        check(&r, 373.124295847666 * (1.0 + 5e-10), 1e-9).unwrap();
    }

    #[test]
    fn known_bad_fails() {
        let r = rec(373.124295847666, None);
        let err = check(&r, 373.2, 1e-9).unwrap_err();
        assert!(err.contains("rel err"), "diagnostic missing: {err}");
    }

    #[test]
    fn exact_zero_agreement_passes() {
        let r = rec(0.0, None);
        check(&r, 0.0, 1e-12).unwrap();
        check(&r, -0.0, 1e-12).unwrap();
        assert!(check(&r, 1e-300, 1e-12).is_err());
    }

    #[test]
    fn per_record_rtol_overrides_default() {
        let r = rec(100.0, Some(1e-3));
        check(&r, 100.05, 1e-9).unwrap();
        assert!(check(&r, 100.2, 1e-9).is_err());
    }

    #[test]
    fn loads_committed_water_smoke_fixture() {
        let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("fixtures/water_propssi_smoke.jsonl");
        let recs = load_jsonl(&path);
        assert_eq!(recs.len(), 12);
        assert_eq!(recs[0].out, "T");
        assert!((recs[0].expected - 373.12429584766636).abs() < 1e-9);
    }
}
