#!/usr/bin/env python3
"""Extract the six cubic-superancillary Chebyshev tables from the pinned
upstream header (include/CoolProp/superancillary/cubicsuperancillary.h) into
crates/rustprop-cubics/src/superanc_tables.rs. Literals are copied verbatim
(the header already prints shortest round-trip decimals).

Usage: python tools/golden-gen/extract_cubic_superanc.py <coolprop-checkout>
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "crates/rustprop-cubics/src/superanc_tables.rs"

NAMES = ["SRK_p", "SRK_rhoL", "SRK_rhoV", "PR_p", "PR_rhoL", "PR_rhoV"]


def main():
    header = Path(sys.argv[1]) / "include/CoolProp/superancillary/cubicsuperancillary.h"
    text = header.read_text()
    out = [
        "//! GENERATED by tools/golden-gen/extract_cubic_superanc.py from the pinned",
        "//! upstream `include/CoolProp/superancillary/cubicsuperancillary.h` — DO",
        "//! NOT EDIT. Literals are upstream's shortest round-trip decimals, verbatim.",
        "",
        "#![cfg_attr(rustfmt, rustfmt::skip)]",
        "",
        "use rustprop_core::fluid::ChebyshevInterval;",
        "",
    ]
    for name in NAMES:
        m = re.search(
            rf"const auto {re.escape(name)} =\s*SuperAncillary\{{\{{(.*?)\}}\}};",
            text,
            re.S,
        )
        assert m, name
        body = m.group(1)
        # Intervals: {{c0, c1, ...}, xmin, xmax}
        intervals = re.findall(r"\{\{(.*?)\}\s*,\s*([0-9eE+.\-]+)\s*,\s*([0-9eE+.\-]+)\s*\}", body, re.S)
        assert intervals, name
        rust_name = name.upper().replace("RHOL", "RHO_L").replace("RHOV", "RHO_V")
        out.append(f"pub static {rust_name}: &[ChebyshevInterval] = &[")
        for coefs, xmin, xmax in intervals:
            cs = [c.strip() for c in coefs.replace("\n", " ").split(",") if c.strip()]
            assert len(cs) == 19, (name, len(cs))
            cs = [c if ("." in c or "e" in c or "E" in c or "inf" in c) else c + ".0" for c in cs]
            out.append(
                f"    ChebyshevInterval {{ xmin: {xmin}, xmax: {xmax}, coef: &[{', '.join(cs)}] }},"
            )
        out.append("];")
        out.append("")
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT} ({sum(1 for l in out if 'ChebyshevInterval {' in l)} intervals)")


if __name__ == "__main__":
    main()
