//! GENERATED by rustprop-datagen from data/coolprop-json/R404A.json — DO NOT EDIT.
//! Regenerate: cargo run -p rustprop-datagen

#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(clippy::approx_constant)]

use rustprop_core::fluid::{Alpha0Term, AlpharTerm, Ancillaries, Eos, FluidData, SaturationAncillary, StatePoint, States, SurfaceTension, Transport, TransportModel, ViscosityModel, ConductivityModel, Viscosity, ViscosityDilute, ViscosityHigherOrder, Conductivity, ConductivityDilute, ConductivityResidual, ConductivityCritical};

pub static R404A: FluidData = FluidData {
    name: "R404A",
    cas: "R404A.PPF",
    aliases: &["R404a"],
    eos: Eos {
        gas_constant: 8.314472,
        molar_mass: 0.0976038,
        p_max: 50000000.0,
        t_max: 500.0,
        t_triple: 200.0,
        acentric: 0.293,
        pseudo_pure: true,
        reducing: StatePoint {
            t: 345.27,
            p: 3734800.0,
            rhomolar: 4939.999999999999,
            hmolar: 33634.81545525588,
            smolar: 141.27493523278102,
        },
        sat_min_liquid: StatePoint {
            t: 200.0,
            p: 22649.187475165232,
            rhomolar: 14209.14074910265,
            hmolar: 10274.347975124234,
            smolar: 59.16747127688488,
        },
        sat_min_vapor: StatePoint {
            t: 200.0,
            p: 21264.273816834986,
            rhomolar: 13.009612612697536,
            hmolar: 31553.17390307545,
            smolar: 165.11140069543768,
        },
        hs_anchor: StatePoint {
            t: 379.797,
            p: 6226559.494469155,
            rhomolar: 4445.999999999999,
            hmolar: 38578.34134643394,
            smolar: 153.46743148019652,
        },
        max_sat_t: Some(StatePoint {
            t: 345.2714161,
            p: 3734844.658,
            rhomolar: 4929.111461,
            hmolar: 33643.2,
            smolar: 141.301,
        }),
        max_sat_p: Some(StatePoint {
            t: 345.2707352,
            p: 3734900.064,
            rhomolar: 4972.369784,
            hmolar: 33594.2,
            smolar: 141.159,
        }),
        alpha0: &[
            Alpha0Term::Lead { a1: 7.00407, a2: 7.98695 },
            Alpha0Term::LogTau { a: -1.0 },
            Alpha0Term::Power { n: &[-18.8664], t: &[-0.3] },
            Alpha0Term::PlanckEinstein { n: &[0.63078, 3.5979, 5.0335], t: &[1.19617, 2.32861, 5.00188] },
        ],
        alphar: &[
            AlpharTerm::Power { n: &[6.10984, -7.79453, 0.0183377, 0.26227, -0.00351688, 0.0116181, 0.00105992, 0.850922, -0.520084, -0.0464225, 0.62119, -0.195505, 0.336159, -0.0376062, -0.00636579, -0.0758262, -0.0221041, 0.0310441, 0.0132798, 0.0689437, -0.0507525, 0.0161382], d: &[1.0, 1.0, 1.0, 2.0, 2.0, 4.0, 6.0, 1.0, 1.0, 1.0, 2.0, 2.0, 3.0, 4.0, 7.0, 2.0, 3.0, 4.0, 4.0, 2.0, 3.0, 5.0], t: &[0.67, 0.91, 5.96, 0.7, 6.0, 0.3, 0.7, 1.7, 3.3, 7.0, 2.05, 4.3, 2.7, 1.8, 1.25, 12.0, 6.0, 8.7, 11.6, 13.0, 17.0, 16.0], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 3.0, 3.0, 3.0] },
        ],
        superancillary: None,
    },
    ancillaries: Ancillaries {
        p_s: SaturationAncillary {
            anc_type: "pL",
            n: &[0.061067, -6.5646, -3.6162, -3.9771],
            t: &[0.54, 0.965, 3.7, 9.0],
            t_r: 345.27,
            reducing_value: 3734800.0,
            using_tau_r: true,
            t_min: 200.0,
            t_max: 345.27,
        },
        p_v_split: Some(SaturationAncillary {
            anc_type: "pV",
            n: &[-0.00026863, -6.5757, -4.1802, -7.9102],
            t: &[0.1, 0.972, 3.8, 9.0],
            t_r: 345.27,
            reducing_value: 3734800.0,
            using_tau_r: true,
            t_min: 200.0,
            t_max: 345.27,
        }),
        rho_l: SaturationAncillary {
            anc_type: "rhoLnoexp",
            n: &[-0.011777381218307114, 2.4984547682678704, 5367.932468376006, -3732982.2139762687, 33474569.015986394, -80262239.93679684],
            t: &[0.066, 0.377, 8.99, 13.98, 15.982, 17.954],
            t_r: 345.27,
            reducing_value: 4939.999999999999,
            using_tau_r: false,
            t_min: 200.0,
            t_max: 345.2699999999992,
        },
        rho_v: SaturationAncillary {
            anc_type: "rhoV",
            n: &[-5.211849919504925, 6.798109425092868, -13.038945243933242, 9.654798311425768, -320.35292894913766, 80023.04183470446],
            t: &[0.485, 0.989, 1.431, 2.495, 7.812, 15.329],
            t_r: 345.27,
            reducing_value: 4939.999999999999,
            using_tau_r: true,
            t_min: 200.0,
            t_max: 345.2699999999992,
        },
        surface_tension: Some(SurfaceTension { a: &[0.0536], n: &[1.249], tc: 345.18 }),
        melting_line: None,
    },
    states: States {
        critical: StatePoint {
            t: 345.27,
            p: 3734800.0,
            rhomolar: 4939.999999999999,
            hmolar: 33630.658952053775,
            smolar: 141.26452133510116,
        },
        triple_liquid: StatePoint {
            t: 200.0,
            p: 22649.187475165232,
            rhomolar: 14209.14074910265,
            hmolar: 10274.347975124234,
            smolar: 59.16747127688488,
        },
        triple_vapor: StatePoint {
            t: 200.0,
            p: 21264.273816834986,
            rhomolar: 13.009612612697536,
            hmolar: 31553.17390307545,
            smolar: 165.11140069543768,
        },
    },
    transport: Some(Transport {
        viscosity: TransportModel::Model(ViscosityModel::Structured(Viscosity {
            epsilon_over_k: 1e99,
            sigma_eta: 1e99,
            dilute: ViscosityDilute::PowersOfT { a: &[9.766e-7, 3.676e-8, 2.938e-12], t: &[0.0, 1.0, 2.0] },
            initial_density: None,
            higher_order: ViscosityHigherOrder::ModifiedBatschinskiHildebrand { a: &[1.08968786472e-6, 4.152109565230651e-5, -4.710175334443676e-5, 4.588082670553865e-5, -2.2593706031401724e-5, 4.4806744468118286e-6], d1: &[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], t1: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], gamma: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], l: &[1.0, 1.0, 1.0, 1.0, 1.0, 1.0], f: &[0.0], d2: &[0.0], t2: &[0.0], g: &[1.0], h: &[0.0], p: &[1.0], q: &[0.0], t_reduce: 345.27, rhomolar_reduce: 4939.999999999999 },
        })),
        conductivity: TransportModel::Model(ConductivityModel::Structured(Conductivity {
            dilute: ConductivityDilute::RatioOfPolynomials { a: &[-0.008624, 7.36e-5], n: &[0.0, 1.0], b: &[1.0], m: &[0.0], t_reducing: 1.0 },
            residual: ConductivityResidual::Polynomial { b: &[0.01553528451384, 0.0059724353152729795, -0.0030186820979668776, 0.0010847310542822014], t: &[0.0, 0.0, 0.0, 0.0], d: &[1.0, 2.0, 3.0, 4.0], t_reducing: 345.27, rhomass_reducing: 482.162772 },
            critical: Some(ConductivityCritical::Hardcoded { name: "None" }),
        })),
    }),
};
