//! GENERATED by rustprop-datagen from data/coolprop-json/R410A.json — DO NOT EDIT.
//! Regenerate: cargo run -p rustprop-datagen

#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(clippy::approx_constant)]

use rustprop_core::fluid::{Alpha0Term, AlpharTerm, Ancillaries, Eos, FluidData, SaturationAncillary, StatePoint, States, SurfaceTension, Transport, TransportModel, ViscosityModel, ConductivityModel, Viscosity, ViscosityDilute, ViscosityHigherOrder, Conductivity, ConductivityDilute, ConductivityResidual, ConductivityCritical};

pub static R410A: FluidData = FluidData {
    name: "R410A",
    cas: "R410A.PPF",
    aliases: &["R410a"],
    eos: Eos {
        gas_constant: 8.314472,
        molar_mass: 0.07258540000000001,
        p_max: 50000000.0,
        t_max: 500.0,
        t_triple: 200.0,
        acentric: 0.296,
        pseudo_pure: true,
        reducing: StatePoint {
            t: 344.494,
            p: 4901200.0,
            rhomolar: 6323.999999999999,
            hmolar: 26766.199757689636,
            smolar: 110.23257268722186,
        },
        sat_min_liquid: StatePoint {
            t: 200.0,
            p: 29160.33537476026,
            rhomolar: 19509.728512139023,
            hmolar: 6743.236201513514,
            smolar: 42.17498003536656,
        },
        sat_min_vapor: StatePoint {
            t: 200.0,
            p: 29009.781591566727,
            rhomolar: 17.796769503206754,
            hmolar: 28123.868782696307,
            smolar: 146.36703706533677,
        },
        hs_anchor: StatePoint {
            t: 378.94340000000005,
            p: 8014421.638869781,
            rhomolar: 5691.599999999999,
            hmolar: 30762.995144699544,
            smolar: 119.87551795269344,
        },
        max_sat_t: Some(StatePoint {
            t: 344.4943434,
            p: 4901288.901,
            rhomolar: 6350.735221,
            hmolar: 26739.2,
            smolar: 110.156,
        }),
        max_sat_p: Some(StatePoint {
            t: 344.4942687,
            p: 4901296.586,
            rhomolar: 6365.195238,
            hmolar: 26726.6,
            smolar: 110.119,
        }),
        alpha0: &[
            Alpha0Term::Lead { a1: 36.8871, a2: 7.15807 },
            Alpha0Term::LogTau { a: -1.0 },
            Alpha0Term::Power { n: &[-46.87575], t: &[-0.1] },
            Alpha0Term::PlanckEinstein { n: &[2.0623, 5.9751, 1.5612], t: &[2.02326, 5.00154, 11.2484] },
        ],
        alphar: &[
            AlpharTerm::Power { n: &[0.987252, -1.03017, 1.17666, -0.138991, 0.00302373, -2.53639, -1.9668, -0.83048, 0.172477, -0.261116, -0.0745473, 0.679757, -0.652431, 0.0553849, -0.071097, -0.000875332, 0.020076, -0.0139761, -0.018511, 0.0171939, -0.00482049], d: &[1.0, 1.0, 1.0, 2.0, 5.0, 1.0, 2.0, 3.0, 5.0, 5.0, 5.0, 1.0, 1.0, 4.0, 4.0, 9.0, 2.0, 2.0, 4.0, 5.0, 6.0], t: &[0.44, 1.2, 2.97, 2.95, 0.2, 1.93, 1.78, 3.0, 0.2, 0.74, 3.0, 2.1, 4.3, 0.25, 7.0, 4.7, 13.0, 16.0, 25.0, 17.0, 7.4], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0] },
        ],
        superancillary: None,
    },
    ancillaries: Ancillaries {
        p_s: SaturationAncillary {
            anc_type: "pL",
            n: &[-7.2818, 2.5093, -3.2695, -2.8022],
            t: &[1.0, 1.8, 2.4, 4.9],
            t_r: 344.494,
            reducing_value: 4901200.0,
            using_tau_r: true,
            t_min: 200.0,
            t_max: 344.494,
        },
        p_v_split: Some(SaturationAncillary {
            anc_type: "pV",
            n: &[-7.4411, 1.9883, -2.4925, -3.2633],
            t: &[1.0, 1.6, 2.4, 5.0],
            t_r: 344.494,
            reducing_value: 4901200.0,
            using_tau_r: true,
            t_min: 200.0,
            t_max: 344.494,
        }),
        rho_l: SaturationAncillary {
            anc_type: "rhoLnoexp",
            n: &[17.62376356934577, -34.49248423230781, 229.4790425881445, -332.5139608181856, 23058076.978355706, -31889422.797179773],
            t: &[0.732, 1.165, 2.775, 3.462, 15.531, 15.944],
            t_r: 344.494,
            reducing_value: 6323.999999999999,
            using_tau_r: false,
            t_min: 200.0,
            t_max: 344.49399999999923,
        },
        rho_v: SaturationAncillary {
            anc_type: "rhoV",
            n: &[-25.00709732482156, 34.83593078562833, -33.0203056956001, 61.19129776625034, -63.32155175461899, 149.8912653231937],
            t: &[0.676, 0.844, 1.394, 2.411, 3.149, 7.808],
            t_r: 344.494,
            reducing_value: 6323.999999999999,
            using_tau_r: true,
            t_min: 200.0,
            t_max: 344.49399999999923,
        },
        surface_tension: Some(SurfaceTension { a: &[0.06238], n: &[1.246], tc: 344.56 }),
        melting_line: None,
    },
    states: States {
        critical: StatePoint {
            t: 344.494,
            p: 4901200.0,
            rhomolar: 6323.999999999999,
            hmolar: 26762.70577282404,
            smolar: 110.22404926360171,
        },
        triple_liquid: StatePoint {
            t: 200.0,
            p: 29160.33537476026,
            rhomolar: 19509.728512139023,
            hmolar: 6743.236201513514,
            smolar: 42.17498003536656,
        },
        triple_vapor: StatePoint {
            t: 200.0,
            p: 29009.781591566727,
            rhomolar: 17.796769503206754,
            hmolar: 28123.868782696307,
            smolar: 146.36703706533677,
        },
    },
    transport: Some(Transport {
        viscosity: TransportModel::Model(ViscosityModel::Structured(Viscosity {
            epsilon_over_k: 1e99,
            sigma_eta: 1e99,
            dilute: ViscosityDilute::PowersOfT { a: &[-2.695e-6, 5.85e-8, -2.129e-11], t: &[0.0, 1.0, 2.0] },
            initial_density: None,
            higher_order: ViscosityHigherOrder::ModifiedBatschinskiHildebrand { a: &[4.1528450396712e-6, 1.2187385701457372e-5, 1.2660855545258755e-5, -1.0753223728015742e-5, 1.9206178288211474e-6, 3.679347106395683e-7], d1: &[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], t1: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], gamma: &[0.0, 0.0, 0.0, 0.0, 0.0, 0.0], l: &[1.0, 1.0, 1.0, 1.0, 1.0, 1.0], f: &[0.0], d2: &[0.0], t2: &[0.0], g: &[1.0], h: &[0.0], p: &[1.0], q: &[0.0], t_reduce: 344.4943434, rhomolar_reduce: 6323.999999999999 },
        })),
        conductivity: TransportModel::Model(ConductivityModel::Structured(Conductivity {
            dilute: ConductivityDilute::RatioOfPolynomials { a: &[-0.008872, 7.41e-5], n: &[0.0, 1.0, 2.0], b: &[1.0], m: &[0.0], t_reducing: 1.0 },
            residual: ConductivityResidual::Polynomial { b: &[0.016414915288896, -0.001905859330388692, 0.00420061845936278, -0.0001644950202819914], t: &[0.0, 0.0, 0.0, 0.0], d: &[1.0, 2.0, 3.0, 4.0], t_reducing: 344.494, rhomass_reducing: 459.0300696 },
            critical: Some(ConductivityCritical::Hardcoded { name: "None" }),
        })),
    }),
};
