//! GENERATED by rustprop-datagen from data/coolprop-json/SES36.json — DO NOT EDIT.
//! Regenerate: cargo run -p rustprop-datagen

#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(clippy::approx_constant)]

use rustprop_core::fluid::{Alpha0Term, AlpharTerm, Ancillaries, Eos, FluidData, SaturationAncillary, StatePoint, States};

pub static SES36: FluidData = FluidData {
    name: "SES36",
    cas: "SES36.ppf",
    aliases: &[],
    eos: Eos {
        gas_constant: 8.314472,
        molar_mass: 0.18485,
        p_max: 500000000.0,
        t_max: 725.0,
        t_triple: 200.0,
        acentric: 0.352,
        pseudo_pure: true,
        reducing: StatePoint {
            t: 450.7,
            p: 2849000.0,
            rhomolar: 2800.0,
            hmolar: 84447.10365025079,
            smolar: 320.6788565898491,
        },
        sat_min_liquid: StatePoint {
            t: 200.0,
            p: 573.2898712226755,
            rhomolar: 8604.642607036263,
            hmolar: 16903.797246793463,
            smolar: 146.1645386412958,
        },
        sat_min_vapor: StatePoint {
            t: 200.0,
            p: 573.2898712226755,
            rhomolar: 0.3451560286454873,
            hmolar: 58924.03634730969,
            smolar: 298.06350991924097,
        },
        hs_anchor: StatePoint {
            t: 495.77,
            p: 4973463.003872624,
            rhomolar: 2520.0,
            hmolar: 98925.2998058967,
            smolar: 349.5949388462608,
        },
        max_sat_t: Some(StatePoint {
            t: 450.7,
            p: 2849000.0,
            rhomolar: 2800.0,
            hmolar: 84447.10365025079,
            smolar: 320.6788565898491,
        }),
        max_sat_p: Some(StatePoint {
            t: 450.7,
            p: 2849000.0,
            rhomolar: 2800.0,
            hmolar: 84447.10365025079,
            smolar: 320.6788565898491,
        }),
        alpha0: &[
            Alpha0Term::Lead { a1: 0.0, a2: 0.0 },
            Alpha0Term::LogTau { a: 12.09 },
            Alpha0Term::PlanckEinstein { n: &[85.26], t: &[4.874639449744842] },
            Alpha0Term::EnthalpyEntropyOffset { a1: -24.5714365589605, a2: 9.90994603225193, reference: "IIR" },
        ],
        alphar: &[
            AlpharTerm::Power { n: &[0.0675748, 1.76939, -2.7609, -0.566938, 0.243576, -1.50937, -0.774081, 0.953907, -1.43736, -0.0458514], d: &[4.0, 1.0, 1.0, 2.0, 3.0, 1.0, 3.0, 2.0, 2.0, 7.0], t: &[1.0, 0.3, 0.947, 1.08, 0.44, 1.7, 1.5, 1.35, 2.1, 0.97], l: &[0.0, 0.0, 0.0, 0.0, 0.0, 2.0, 2.0, 1.0, 2.0, 1.0] },
            AlpharTerm::Gaussian { n: &[2.46053, -0.903158, -0.288664, 0.061038], d: &[1.0, 1.0, 3.0, 3.0], t: &[0.8, 2.0, 2.5, 4.0], eta: &[1.023, 1.383, 1.0, 7.0], beta: &[1.7, 1.55, 1.07, 87.0], gamma: &[1.1, 0.64, 0.5, 1.26], epsilon: &[0.713, 0.917, 0.69, 0.748] },
        ],
        superancillary: None,
    },
    ancillaries: Ancillaries {
        p_s: SaturationAncillary {
            anc_type: "pL",
            n: &[0.007422939800114443, -8.947924311081916, 2.4455850233209473, -6.449704516156368, 13.607518741300712, -27.19167556046972],
            t: &[0.383, 1.0, 1.1666666666666667, 3.0, 4.333333333333333, 18.5],
            t_r: 450.7000000000001,
            reducing_value: 2849000.0,
            using_tau_r: true,
            t_min: 200.0,
            t_max: 450.69000000000005,
        },
        p_v_split: Some(SaturationAncillary {
            anc_type: "pV",
            n: &[0.007422939800114443, -8.947924311081916, 2.4455850233209473, -6.449704516156368, 13.607518741300712, -27.19167556046972],
            t: &[0.383, 1.0, 1.1666666666666667, 3.0, 4.333333333333333, 18.5],
            t_r: 450.7000000000001,
            reducing_value: 2849000.0,
            using_tau_r: true,
            t_min: 200.0,
            t_max: 450.69000000000005,
        }),
        rho_l: SaturationAncillary {
            anc_type: "rhoLnoexp",
            n: &[-241.2370611920301, 279.06782469843284, -38.11111567200517, 2.4856124479524024, 1.2945715078736757, -0.7959298395742012],
            t: &[0.059, 0.062, 0.083, 0.3605, 1.5, 2.0],
            t_r: 450.7000000000001,
            reducing_value: 2800.0,
            using_tau_r: false,
            t_min: 200.0,
            t_max: 450.69000000000005,
        },
        rho_v: SaturationAncillary {
            anc_type: "rhoV",
            n: &[-4.086903656826663, 6.180725737220783, -6.241598036559721, 1.036017562604198, -4.093270917666299, 9.117098066697686],
            t: &[0.08, 0.124, 0.3685, 1.1666666666666667, 1.5, 5.5],
            t_r: 450.7000000000001,
            reducing_value: 2800.0,
            using_tau_r: true,
            t_min: 200.0,
            t_max: 450.69000000000005,
        },
        surface_tension: None,
        melting_line: None,
    },
    states: States {
        critical: StatePoint {
            t: 450.7000000000001,
            p: 2849000.0,
            rhomolar: 2800.0,
            hmolar: 84434.88770828162,
            smolar: 320.65361127452763,
        },
        triple_liquid: StatePoint {
            t: 200.0,
            p: 573.2898712226755,
            rhomolar: 8604.642607036263,
            hmolar: 16903.797246793463,
            smolar: 146.1645386412958,
        },
        triple_vapor: StatePoint {
            t: 200.0,
            p: 573.2898712226755,
            rhomolar: 0.3451560286454873,
            hmolar: 58924.03634730969,
            smolar: 298.06350991924097,
        },
    },
    transport: None,
};
