//! The HS flash must never answer with a state that does not reproduce its
//! own inputs, and must stay inside a time budget.
//!
//! Both properties were violated before the audit fixes:
//!
//!   * `hmolar_smolar_state`'s legacy fallback was the one leg not gated on
//!     `reproduces()`. For Water at h = 0.5 J/kg, s = -1 J/kg/K it answered
//!     T = 275.5032 K — a state whose enthalpy is 9880 J/kg, not 0.5. The
//!     wheel answers T = 273.094065 K, which does reproduce the inputs; that
//!     root is 0.066 K below the triple point and no leg this port searches
//!     reaches it, so the port now refuses rather than answering wrongly.
//!     See NEXT-STEPS.md's divergence table.
//!
//!   * That same call took ~400 ms, against ~30 us for a reachable state.
//!     `props_si_many` maps a whole grid through this path, so an unbudgeted
//!     legacy leg is a real hazard for the WASM consumer this port exists for.

#![cfg(feature = "heos")]

use std::time::Instant;

/// Every answer the HS flash returns must reproduce the (h, s) it was asked
/// for, at the same tolerance the flash's own internal gate uses.
#[test]
fn every_hs_answer_reproduces_its_inputs() {
    // Ground truth generated by the library itself: pick (T, P), read off
    // (H, S), then ask the flash to recover T. Anything it returns has to be
    // the state that was asked for.
    let mut checked = 0;
    for &p in &[1.0e4_f64, 1.0e5, 101_325.0, 1.0e6, 1.0e7] {
        for &t_in in &[
            273.2_f64, 274.0, 280.0, 300.0, 350.0, 400.0, 500.0, 600.0, 800.0,
        ] {
            let (Ok(h), Ok(s)) = (
                rustprop::props_si("H", "T", t_in, "P", p, "Water"),
                rustprop::props_si("S", "T", t_in, "P", p, "Water"),
            ) else {
                continue;
            };
            let Ok(t_out) = rustprop::props_si("T", "H", h, "S", s, "Water") else {
                continue;
            };
            checked += 1;
            assert!(
                (t_out - t_in).abs() <= 1e-6 * t_in,
                "HS flash at ({p} Pa, {t_in} K): h = {h}, s = {s} recovered T = {t_out}, \
                 off by {} K",
                t_out - t_in
            );
        }
    }
    assert!(
        checked >= 30,
        "expected a real sweep, only checked {checked}"
    );
}

/// The specific state that used to come back wrong. Either answer is
/// acceptable — the correct root, or a refusal — but never a third number
/// presented as success.
#[test]
fn sub_triple_hs_target_is_never_answered_wrongly() {
    let (h, s) = (0.5_f64, -1.0_f64);
    match rustprop::props_si("T", "H", h, "S", s, "Water") {
        Err(_) => {} // refusing is the documented divergence
        Ok(t) => {
            let d = rustprop::props_si("D", "H", h, "S", s, "Water")
                .expect("a T answer implies a D answer");
            let hb = rustprop::props_si("H", "T", t, "D", d, "Water").unwrap();
            let sb = rustprop::props_si("S", "T", t, "D", d, "Water").unwrap();
            assert!(
                (hb - h).abs() <= 1e-6 * h.abs() + 1e-3 && (sb - s).abs() <= 1e-6 * s.abs() + 1e-5,
                "HS flash answered T = {t}, D = {d}, but that state has h = {hb}, \
                 s = {sb} — not the requested h = {h}, s = {s}. The wheel answers \
                 T = 273.094065 K here."
            );
        }
    }
}

/// A state the cascade can serve must not fall onto the legacy leg.
///
/// Reachable states settle in tens of microseconds; the legacy leg costs
/// hundreds of milliseconds. The gap is four orders of magnitude, so a budget
/// anywhere between them separates the two cleanly and will not flake on a
/// loaded runner. This is the regression that matters: a future edit that
/// pushes ordinary states onto the slow path would otherwise show up only as
/// a mysteriously sluggish consumer.
#[test]
fn reachable_hs_states_stay_off_the_legacy_leg() {
    const BUDGET_MS: u128 = 25;

    let mut worst = (0u128, (0.0f64, 0.0f64), 0.0f64);
    for &p in &[1.0e4_f64, 101_325.0, 1.0e6, 1.0e7] {
        for &t_in in &[273.2_f64, 280.0, 300.0, 400.0, 500.0, 800.0] {
            let (Ok(h), Ok(s)) = (
                rustprop::props_si("H", "T", t_in, "P", p, "Water"),
                rustprop::props_si("S", "T", t_in, "P", p, "Water"),
            ) else {
                continue;
            };
            // Warm anything lazily built, then measure.
            let _ = rustprop::props_si("T", "H", h, "S", s, "Water");
            let t0 = Instant::now();
            let _ = rustprop::props_si("T", "H", h, "S", s, "Water");
            let ms = t0.elapsed().as_millis();
            if ms > worst.0 {
                worst = (ms, (h, s), t_in);
            }
        }
    }
    assert!(
        worst.0 <= BUDGET_MS,
        "props_si(\"T\", \"H\", {:e}, \"S\", {:e}, \"Water\") — the reachable state at \
         T = {} K — took {} ms, over the {} ms budget. A reachable state has fallen \
         through the cascade onto the legacy leg.",
        worst.1.0,
        worst.1.1,
        worst.2,
        worst.0,
        BUDGET_MS
    );
}

/// Nothing runs away without bound, including inputs no state satisfies.
///
/// The ceiling is loose on purpose. The legacy leg is upstream's own
/// algorithm and upstream is slower here than this port — the wheel takes
/// ~1.3 s on the `h = 1e300` case where this port takes ~0.46 s — so the cost
/// is inherited, not a port defect, and the assertion only catches a genuine
/// non-terminating regression.
#[test]
fn no_hs_input_runs_away() {
    const CEILING_MS: u128 = 3_000;

    let cases: &[(f64, f64)] = &[
        (0.5, -1.0),
        (1e300, -1.0),
        (-1e300, 1.0),
        (0.0, 0.0),
        (f64::NAN, 7.0e3),
        (f64::INFINITY, 7.0e3),
        (f64::NEG_INFINITY, -1.0),
        (1e-300, 1e-300),
    ];
    for &(h, s) in cases {
        let t0 = Instant::now();
        let _ = rustprop::props_si("T", "H", h, "S", s, "Water");
        let ms = t0.elapsed().as_millis();
        assert!(
            ms <= CEILING_MS,
            "props_si(\"T\", \"H\", {h:e}, \"S\", {s:e}, \"Water\") took {ms} ms, over the \
             {CEILING_MS} ms ceiling"
        );
    }
}
