#!/usr/bin/env bash
# Builds the JS deliverable (crates/rustprop-wasm) for each representative
# feature set and prints the markdown table committed in WASM-SIZES.md.
#
# The point of the numbers: engine and fluid selection is a COMPILE-time
# choice, so a bundle carries only what its application asked for.
#
#   tools/wasm-size-table.sh > WASM-SIZES.md
set -euo pipefail
cd "$(dirname "$0")/.."
export PATH="$HOME/.cargo/bin:$PATH"

SETS=(
  "if97|if97"
  "heos + Water|heos,water"
  "heos + refrigerants (R134a, R32, R125, R1234yf)|heos,rustprop-data/r134a,rustprop-data/r32,rustprop-data/r125,rustprop-data/r1234yf"
  "humid-air|humid-air"
  "cubics (116 fluids)|cubics"
  "incompressible (126 fluids)|incompressible"
  "pcsaft (180 fluids) + heos|heos,pcsaft"
  "heos + all 130 fluids|heos,all-fluids"
  "all-backends|all-backends"
)

echo "# WASM bundle sizes"
echo
echo "Generated by \`tools/wasm-size-table.sh\`. Bytes are the optimized"
echo "\`rustprop_wasm_bg.wasm\` from \`wasm-pack build --target web --release\`,"
echo "i.e. what a browser actually downloads."
echo
echo "| feature set | bytes | KB |"
echo "|---|---:|---:|"
for entry in "${SETS[@]}"; do
  label="${entry%%|*}"
  feats="${entry#*|}"
  wasm-pack build crates/rustprop-wasm --target web --out-dir pkg-size \
    --features "$feats" >/dev/null 2>&1
  n=$(stat -c %s crates/rustprop-wasm/pkg-size/rustprop_wasm_bg.wasm)
  printf '| %s | %s | %.1f |\n' "$label" "$n" "$(echo "$n / 1024" | bc -l)"
done
rm -rf crates/rustprop-wasm/pkg-size
